import Footer from '@/components/shared/footer'
import Header from '@/components/shared/header'
import { Inter } from 'next/font/google'

import { routing } from '@/i18n/routing'
import { NextIntlClientProvider, hasLocale } from 'next-intl'
import { notFound } from 'next/navigation'

import './globals.css'

const inter = Inter({
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function LocaleLayout({ children, params }) {
	const { locale } = await params
	if (!hasLocale(routing.locales, locale)) {
		notFound()
	}
	return (
		<html
			lang={locale}
			className='scroll-smooth'
		>
			<body className={`${inter.className} antialiased bg-[#F1F2F4]`}>
				<NextIntlClientProvider>
					<Header />
					<main>{children}</main>
					<Footer />
				</NextIntlClientProvider>
			</body>
		</html>
	)
}
